# Introduction
All of the data for this project was collected directly from the official Riot Games Teamfight Tactics (TFT) API, which is a public API maintained by Riot Games. It provides real-time and historical game data for TFT players, matches, and ranked ladders.

Data Tables Used:

League endpoints: retrieves Master, Grandmaster, and Challenger ranked players
Match endpoints: retrieves match history and full match JSON data
PUUID lookup: maps players to their unique global identifiers

API Documentation:
https://developer.riotgames.com/apis#tft-match-v1
https://developer.riotgames.com/apis#tft-league-v1

All of the data was taken from the Riot Games API and collected via Python script
requests for API calls
pathlib for file management
logging for debugging and transparency

Process Overview

The raw data is stored as JSON files produced by the API. A single JSON file corresponds to a singular TFT game.
All data collection code is included, and the process is fully reproducible if the user has an valid Riot Game API key and account.

Constraints of the script:
I am limiting the region to NA
I originally collected a simple random sample of 250 Grandmaster, and Challenger rank players (the two highest level player ranks) and their 25 most recent game data. However, the API has run limitations which caused my code to only pull 422 players.

After some inital evaluation, I wanted to include the next lower rank (Master) to better diversify the playerbase (according to as Challenger + Grandmaster accounted for <1% of the playerbase while Master is 2.2%. 
However, when I ran the script the RIOT API had no data to pull due to the new season coming out. When this happens, the ranks are reset which caused my scrapper log to show no data. While this is not ideal, i think it is still a robust enough dataset for this project.

Used github script tft_data_collector.py as the basis for my script (source: ).
