# Methods

The dataset used in this project was collected using Riot Games’ official Teamfight Tactics API. Identifiers of players rank (Grandmaster, and Challenger) from North America (NA) were preset in the Python Script. From this population, a simple random sample of 250 players of each rank were selected. The 25 most recent games played by these players were then selected. This data was then stored as raw JSON files to latter be processed in the data processing step. 

## Random Forest Regression
A machine-learning algorithm used for predicting continuous numerical outcomes. Random Forest Regression is used to determine which gameplay variables most strongly influence a player’s final placement.

## Random Forest Classification
A supervised learning method used to categorize data into discrete labels. It functions very similar to Random Forest Regression, but the target in prediciton is categorical. Random Forest Regression is used to determine which gameplay variables most strongly influence a player’s final placement.

## Hierarchical Clustering
An unsupervised learning technique that groups similar data points into clusters without predefined labels. Hierarchical Clustering is used to identify popular team comps.