# Introduction:
This project explores unsupervised learning techniques to identify common meta compositions (“comps”) used by top-ranked players in Teamfight Tactics (TFT), Set 15. The primary research questions guiding this analysis are:

What team composition is the most frequently used by top-level TFT players?
Which composition places the highest at top-level play?

In TFT, champions have unique abilities and share traits that activate synergies when fielded together. For example, Ahri and Jinx share the Star Guardian trait, granting increased bonuses when multiple Star Guardians appear in the team. Understanding which champion combinations appear consistently in successful boards may reveal the meta trends that drive competitive play.

# Methods
I had used my cleaned dataset to create a new dataset consisting of 32,455 rows and 63 champion indicator columns, where each column represented the frequency or presence of a champion in the player’s final board.
Because analyzing every individual game state introduces high redundancy, duplicate rows were removed, producing a dataset of 10,757 unique compositions.

This reduction is expected because high-level players tend to converge on optimal meta comps despite the game’s inherent randomness (RNG)

Initial Attempts Using HDBSCAN

My initial attemp was to use use HDBSCAN, which is well-suited for clusters of varying densities. However, it was not producing ideal results. As the data is purely categorical, Euclidean distance is unsuitable. Switching to Jaccard distance produced unstable clusters with poor separation.

Due to these limitations, I had decided to apply hierarchial clustering instead. Like HDBSCAN, it was initially run using Jaccard distance, but the number of clusters exceeded 100, making interpretation difficult. To address this, Principal Component Analysis (PCA) was applied prior to clustering. PCA was applied with n_components = 25 and the retained components explained 82.6% of the variance. After PCA was applied, clustering transitioned to using Euclidean distance.

After creating a dendrogram, a threshold parameter (t) was evaluated to determine the cut point in the dendrogram. This would determine the number of clusters. The results are shown below:

t = 2 → clusters = 228
t = 3 → clusters = 11
t = 4 → clusters = 1
t = 5 → clusters = 1

Based on cluster separation and number of clusters, t = 3 was selected, producing 11 meaningful clusters representing meta team compositions.

#Methods 
Hierarchic Clustering:
  - A clustering algorithm.

HDBSCAN (Hierarchical Density-Based Spatial Clustering of Applications with Noise)
  - HDBSCAN is a clustering algorithm build upon DBSCAN. It can dynamically adapt adjust to different densities and form clusters within the data. It is best used for datasets with complex structures or varying densities because it creates a hierarchical tree of clusters that enable users to examine the data at different levels of granularity. Parameters that can be adjusted by the ende user are:
  The minimum number of points to form a cluster.
  The minimum number of samples in a neighborhood for a point to be considered a core point.

Principal Component Analysis (PCA):
  - 

TSNE
  - 

#Results Section:
Below is a table showing the cluster and the number of points in each cluster. 

3     1680
6     1505
5     1363
10     960
1      955
4      852
2      819
9      802
11     744
7      566
8      511 

Clusters 3,6, and 5 are the largest.

Below are the 11 clusters produced. 
The values represent frequency of champion appearance within the cluster. A higher value, indicates if they are a staple,secondary, or niche champion pick for each team comp.
 
===== COMP 1 =====
  Poppy: 0.95
  Jinx: 0.95
  Neeko: 0.81
  Rell: 0.75
  Kobuko: 0.72
  KSante: 0.68
  Xayah: 0.52
  Seraphine: 0.48
  Varus: 0.47
  Braum: 0.46

===== COMP 2 =====
  Garen: 0.95
  Rakan: 0.90
  Ezreal: 0.88
  Leona: 0.84
  Yuumi: 0.83
  Jayce: 0.57
  Katarina: 0.53
  Ryze: 0.31
  Malzahar: 0.29
  KSante: 0.29

===== COMP 3 =====
  Shen: 0.89
  Leona: 0.85
  Rell: 0.84
  Swain: 0.83
  XinZhao: 0.81
  Braum: 0.66
  Garen: 0.43
  Seraphine: 0.38
  TwistedFate: 0.37
  Zyra: 0.31

===== COMP 4 =====
  Samira: 0.93
  Sett: 0.92
  Volibear: 0.77
  Naafiri: 0.73
  XinZhao: 0.72
  Lux: 0.54
  Gwen: 0.48
  Braum: 0.46
  Viego: 0.40
  Shen: 0.38

===== COMP 5 =====
  DrMundo: 0.93
  Udyr: 0.91
  Sett: 0.87
  Naafiri: 0.80
  Vi: 0.71
  LeeSin: 0.71
  Braum: 0.54
  TwistedFate: 0.53
  Zyra: 0.45
  Aatrox: 0.44

===== COMP 6 =====
  Swain: 0.91
  Janna: 0.90
  Ashe: 0.85
  Vi: 0.77
  Zyra: 0.71
  KSante: 0.69
  JarvanIV: 0.67
  Braum: 0.55
  Udyr: 0.53
  LeeSin: 0.47

===== COMP 7 =====
  Janna: 0.83
  Malphite: 0.81
  Sivir: 0.60
  Ziggs: 0.57
  Shen: 0.57
  Ryze: 0.46
  JarvanIV: 0.44
  Neeko: 0.41
  KSante: 0.34
  Kennen: 0.31

===== COMP 8 =====
  Karma: 0.97
  Lucian: 0.94
  JarvanIV: 0.90
  Ryze: 0.66
  Swain: 0.51
  Aatrox: 0.49
  Senna: 0.46
  Gwen: 0.44
  Lux: 0.43
  Gangplank: 0.41

===== COMP 9 =====
  Kayle: 0.82
  Udyr: 0.79
  Zac: 0.72
  Jhin: 0.62
  Aatrox: 0.60
  Varus: 0.54
  KSante: 0.54
  LeeSin: 0.40
  Malzahar: 0.40
  Sett: 0.31

===== COMP 10 =====
  Zac: 0.64
  Darius: 0.64
  Malzahar: 0.64
  Kobuko: 0.58
  Poppy: 0.50
  Jayce: 0.46
  Aatrox: 0.37
  Rammus: 0.32
  Seraphine: 0.28
  KSante: 0.21

===== COMP 11 =====
  Aatrox: 0.75
  Ryze: 0.71
  Udyr: 0.65
  JarvanIV: 0.62
  Akali: 0.56
  Darius: 0.55
  Senna: 0.49
  Kennen: 0.49
  Kobuko: 0.44
  KSante: 0.41

After looking at these comps, I then found the average place of each cluster.

cluster
10    4.206250
4     4.497653
8     4.524462
11    4.526882
1     4.689005
2     4.739927
9     4.754364
3     4.783929
5     4.947175
6     5.016611
7     5.169611


### Conclusions:

The most popular competitve comp was Comp 3, a Shen–Leona Vanguard team.

===== COMP 3 =====
  Shen: 0.89
  Leona: 0.85
  Rell: 0.84
  Swain: 0.83
  XinZhao: 0.81
  Braum: 0.66
  Garen: 0.43
  Seraphine: 0.38
  TwistedFate: 0.37
  Zyra: 0.31

Shen, Leona, Rell, Swain, and Xin Zhao form a stable and highly repeatable core, each appearing in over 80% of compositions in this cluster. Braum serves as a common secondary unit, while Garen, Seraphine, Twisted Fate, and Zyra act as niche and/or situational inclusions.

Because this cluster is the largest, it represents the most frequently played comp among top-ranked players.
However, despite its popularity, Comp 3 had only the fourth-best average placement, indicating that frequency does not necessarily equate to performance.

The highest placing was comp 10:
===== COMP 10 =====
  Zac: 0.64
  Darius: 0.64
  Malzahar: 0.64
  Kobuko: 0.58
  Poppy: 0.50
  Jayce: 0.46
  Aatrox: 0.37
  Rammus: 0.32
  Seraphine: 0.28
  KSante: 0.21

This comp is a tank/bruiser-oriented lineup anchored by Zac, Darius, Malzahar, and Kobuko.
Interestingly, Comp 10 shows comparatively low internal cohesion—its most frequent champions appear only 64% of the time. The lack of a clearly defined, consistent core likely contributes to its lower pick rate, even though it performs extremely well when executed.

Comparing the most popular and best performing comp leads to some results of the metagame. There is almost no overlap between the top-performing and the most popular comps, with Seraphine being the only shared champion—and only as a low-frequency flex unit in both. Also, the placement range across all clusters is narrow (less than one position), indicating a highly balanced metagame at the top level of competitive play.